# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20161024_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='characterName',
            field=models.CharField(blank=True, db_column=b'characterName', max_length=255, null=True, verbose_name=b'Character Name:'),
        ),
    ]
