# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20161024_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='achivementPoints',
            field=models.IntegerField(blank=True, db_column=b'achievementPoints', null=True, verbose_name=b'Achievement Points'),
        ),
        migrations.AddField(
            model_name='character',
            name='characterHonorableKills',
            field=models.IntegerField(blank=True, db_column=b'characterHonorableKills', null=True, verbose_name=b'Character Honorable Kills'),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, db_column=b'gender', max_length=255, null=True, verbose_name=b'Gender'),
        ),
        migrations.AddField(
            model_name='character',
            name='iconURL',
            field=models.CharField(blank=True, db_column=b'iconURL', max_length=1000, null=True, verbose_name=b'Icon URLS'),
        ),
        migrations.AddField(
            model_name='character',
            name='itemLevelEquipped',
            field=models.IntegerField(blank=True, db_column=b'itemLevelEquipped', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, db_column=b'race', max_length=255, null=True, verbose_name=b'Race'),
        ),
    ]
