# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20161024_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nickName',
            field=models.CharField(blank=True, db_column=b'nickName', max_length=255, null=True, verbose_name=b'Nickname'),
        ),
        migrations.AlterField(
            model_name='character',
            name='itemLevelEquipped',
            field=models.IntegerField(blank=True, db_column=b'itemLevelEquipped', null=True, verbose_name=b'Equipped'),
        ),
    ]
