# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20161024_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('encounterID', models.IntegerField(blank=True, db_column=b'encounterID', null=True)),
                ('spec', models.IntegerField(blank=True, db_column=b'spec', null=True)),
                ('guildName', models.CharField(blank=True, db_column=b'guildName', max_length=255, null=True)),
                ('rankNumber', models.IntegerField(blank=True, db_column=b'rankNumber', null=True, verbose_name=b'Rank Number')),
                ('rankOutOf', models.IntegerField(blank=True, db_column=b'rankOutOf', null=True)),
                ('duration', models.IntegerField(blank=True, db_column=b'duration', null=True, verbose_name=b'Duration')),
                ('reportID', models.IntegerField(blank=True, db_column=b'reportID', null=True, verbose_name=b'Report ID')),
                ('fightID', models.IntegerField(blank=True, db_column=b'fightID', null=True, verbose_name=b'Fight ID')),
                ('difficulty', models.IntegerField(blank=True, db_column=b'difficulty', null=True, verbose_name=b'Difficulty')),
                ('size', models.IntegerField(blank=True, db_column=b'raidSize', null=True, verbose_name=b'Raid Sie')),
                ('itemLevel', models.IntegerField(blank=True, db_column=b'itemLevel', null=True, verbose_name=b'Item Level')),
                ('total', models.IntegerField(blank=True, db_column=b'total', null=True, verbose_name=b'total')),
                ('characterID', models.ForeignKey(blank=True, db_column=b'characterID', null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character', verbose_name=b'Character')),
            ],
        ),
    ]
