# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20161024_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankings',
            name='characterID',
            field=models.ForeignKey(blank=True, db_column=b'characterID', null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character', verbose_name=b'Character'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='total',
            field=models.FloatField(blank=True, db_column=b'total', null=True, verbose_name=b'total'),
        ),
    ]
